Update/Cancel/Approve holidays
UnosquareBelfast/AdminCore pull request #117
Opened 2018-07-30 11:37 UTC by paulbrownlee

2018-07-30 12:50 UTC, BrownMark requested changes

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/ViewModels/SaveWorkingFromHomeViewModel.java
> +    private int eventTypeId;
This is inferred by the type.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/ViewModels/UpdateHolidayViewModel.java
> +    private int eventTypeId;
This is inferred by the type.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/ViewModels/UpdateHolidayViewModel.java
> +    private int eventStatusId;
We'll make specific calls for the status, let's not specify like this.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/controller/HolidayController.java
> +            event.setEventId(updateHolidayViewModel.getHolidayId());
Should this not happen in the mapping?

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/service/EventService.java
> +        event.setStartDate(eventDTO.getStartDate());
Same with mappings.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/service/EventService.java
> +        EventDTO temp = findById(eventDTO.getEventId());
I'd use the reppsitory here.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/service/EventService.java
> +        EventDTO temp = findById(eventDTO.getEventId());
I'd use the repository here.

2018-07-30 12:50 UTC, BrownMark commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/service/EventService.java
> +        EventDTO temp = findById(eventDTO.getEventId());
I'd use the repository here.

2018-07-30 12:51 UTC, BrownMark commented on web-app/src/utilities/AxiosInstance.js
> +const baseURL = 'http://localhost:8081';
This needs removed and reverted.

2018-07-31 10:13 UTC, paulbrownlee commented on BackEnd/src/main/java/com/unosquare/admin_core/back_end/configuration/mappings/presentation/CancelHolidayMappings.java
> +                map().setLastModified(LocalDate.now());
Changed to map()

2018-07-31 10:58 UTC, BrownMark approved these changes

2018-07-31 11:41 UTC, BrownMark approved these changes

2018-07-31 11:41 UTC, merged