Feat/global styles/native
UnosquareBelfast/AdminCore pull request #138
Opened 2018-08-01 15:04 UTC by lee-cheung

global styles for colors, text and layout

2018-08-01 16:15 UTC, kirsty-unosquare requested changes
Forgot to remove the globalStyles folder. Other than that all good. @William-Unosquare just needs to have a quick look over it. :)

2018-08-01 16:15 UTC, kirsty-unosquare commented on NativeApp/src/utilities/globalStyles/colours.js
> +const colors = {
Don't need this file anymore. Can delete along with the globalStyles folder.

2018-08-01 16:15 UTC, kirsty-unosquare commented on NativeApp/src/utilities/globalStyles/text.js
> -export const P_SIZE = 17;
Same here. Can be deleted.

2018-08-01 16:23 UTC, lee-cheung commented on NativeApp/src/utilities/globalStyles/colours.js
> +const colors = {
woops, yes I will delete it

2018-08-01 16:25 UTC, kirsty-unosquare commented
Gonna approve.

2018-08-01 16:25 UTC, kirsty-unosquare approved these changes

2018-08-02 10:09 UTC, William-Unosquare approved these changes
Looks good. It's a bit hard reviewing some of these bigger PRs without being involved in the project though so stuff could be missed.

2018-08-02 10:42 UTC, merged