[TS-70] Legend now appears on the right of the calendar, instead of below
UnosquareBelfast/AdminCore pull request #228
Opened 2018-09-17 13:08 UTC by William-Unosquare

I made this change for a few reasons:
- It removes the need to scroll up and down the page to interact with the filters.
- This layout makes better use of space. Previously keys would have appeared really wide for no reason.
- Allows for the calendar to have more height and therefore fit more events in view.

![chrome_2018-09-17_14-07-27](https://user-images.githubusercontent.com/39301552/45624716-0b6d6180-ba83-11e8-8165-8e8abd9b4f47.png)

2018-09-17 19:00 UTC, girwin575 commented on web-app/src/pages/Dashboard/styled.js
> +    border-left: 1px solid #ddd;
variable for #ddd?

2018-09-17 19:01 UTC, ghost requested changes
Small comment

2018-09-18 08:49 UTC, d1wilko approved these changes
looks good to me :)

2018-09-18 12:49 UTC, ghost approved these changes

2018-09-18 14:08 UTC, merged