[TS-71][TS-72] Fix for toast appearing, booking modal layout improvements
UnosquareBelfast/AdminCore pull request #230
Opened 2018-09-17 15:24 UTC by William-Unosquare

**Wait until #228 is merged in to review.**

- Fix for the "Dates Approved" toast appearing when you changed dates inside the booking modal.
- Styling improvements around the "days notice" warning. It's far less in your face now, but it's still noticeable.
- The counter for how many days you're booking off is integrated into the submit buttons confirmation.. this just helps tidy up the modal a bit. 

![chrome_2018-09-17_16-11-40](https://user-images.githubusercontent.com/39301552/45632750-06fe7400-ba96-11e8-81a0-20a9c3867b49.png)

2018-09-17 19:00 UTC, ghost requested changes
Really small thing but I think the Request a half day box is one pixel too far to the left. I used the old paper test. Small thing but I thought I'd raise it.

2018-09-18 09:02 UTC, d1wilko requested changes
A few questions - mainly grand

2018-09-18 09:02 UTC, d1wilko commented on web-app/src/components/BookingModal/BookingModalForm/container.js
> +            type: formIsValid ? 'success' : 'warning',
`formIsValid` will always be false here because of line 114 no?

2018-09-18 09:02 UTC, d1wilko commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +          label: `Update to ${
formatting is a bit funny here - `${bookingDuration === 0.5 ? 'Half' : bookingDuration}` - would be cleaner

2018-09-18 09:02 UTC, d1wilko commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +          label: `Request ${
again odd formatting `${bookingDuration === 0.5 ? 'Half' : bookingDuration}`

2018-09-18 09:02 UTC, d1wilko commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +            {' ' + bookingDuration} {bookingDuration > 1 ? 'days' : 'day'} off.
why the string concatenation here?

2018-09-18 09:25 UTC, William-Unosquare commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +            {' ' + bookingDuration} {bookingDuration > 1 ? 'days' : 'day'} off.
The space character gets lost before & after the newline in code.

2018-09-18 09:26 UTC, William-Unosquare commented on web-app/src/components/BookingModal/BookingModalForm/container.js
> +            type: formIsValid ? 'success' : 'warning',
Well spotted.

2018-09-18 09:28 UTC, William-Unosquare commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +          label: `Update to ${
Have to keep it this way due to Prettier. I think it's caused by the max line length rule.

2018-09-18 09:28 UTC, William-Unosquare commented on web-app/src/components/BookingModal/BookingModalForm/index.js
> +          label: `Request ${
see above

2018-09-18 11:28 UTC, William-Unosquare commented
Fixed all I think I can fix here. I'd rather keep to the ESLint / Prettier rules and have a couple of cases of poor formatting.

2018-09-18 12:48 UTC, ghost approved these changes

2018-09-18 13:13 UTC, d1wilko approved these changes
looks grand lad

2018-09-18 14:09 UTC, merged