Feature/stub out methods
UnosquareBelfast/AdminCore pull request #275
Opened 2018-11-06 10:48 UTC by CampbellJGilpin

2018-11-06 16:27 UTC, BrownMark requested changes

2018-11-06 16:27 UTC, BrownMark commented on v2/AdminCore.Common/Interfaces/ITeamService.cs
> +        IList<TeamDto> findAll();
Formatting inconsistent

2018-11-06 16:27 UTC, BrownMark commented on v2/AdminCore.DTOs/Team/TeamDto.cs
> +        public int ClientId { get; set; }
Again on formatting.

2018-11-06 16:27 UTC, BrownMark commented on v2/AdminCore.Services/Mappings/ServiceMapperProfile.cs
> +    [Obsolete("Not used anymore - Being replaced by individual mapping classes", true)]
nice

2018-11-06 16:27 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/TeamController.cs
> +        [HttpPut("/")]
Don't needs routes for these.

2018-11-06 16:27 UTC, BrownMark commented on v2/AdminCore.WebApp/Models/Team/TeamViewModel.cs
> +        private int teamId;
Formatting.

2018-11-07 10:32 UTC, CampbellJGilpin commented on v2/AdminCore.Common/Interfaces/ITeamService.cs
> +        IList<TeamDto> findAll();
Method name, or also indenting?

2018-11-07 10:37 UTC, CampbellJGilpin commented on v2/AdminCore.DTOs/Team/TeamDto.cs
> +        public int ClientId { get; set; }
Indenting?

2018-11-07 12:07 UTC, BrownMark requested changes

2018-11-07 12:07 UTC, BrownMark commented on v2/AdminCore.Common/Interfaces/IEventService.cs
> +    EventDto FindById(int ID);
convention is camel case for variables id or employeeId

2018-11-07 12:07 UTC, BrownMark commented on v2/AdminCore.Services/EventService.cs
> +    public void UpdateEvents(UpdateEventDto UpdateEventDto)
Same again with conventions

2018-11-07 12:07 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/ClientController.cs
> +    [AllowAnonymous]
Can we remove AllowAnnoymous everywhere? Just remove the Authorise

2018-11-07 12:07 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/TeamController.cs
> +        [AllowAnonymous]
Same here

2018-11-07 12:08 UTC, BrownMark commented on v2/AdminCore.Services/ClientService.cs
> +    public void UpdateClient(ClientDto missing_name)
Can we name this client?

2018-11-07 12:08 UTC, BrownMark requested changes

2018-11-07 12:08 UTC, BrownMark commented on v2/AdminCore.Common/Interfaces/IClientService.cs
> +    void UpdateClient(ClientDto);
Does this compile?

2018-11-07 14:25 UTC, CampbellJGilpin commented on v2/AdminCore.Services/EventService.cs
> +    public void UpdateEvents(UpdateEventDto UpdateEventDto)
This file has been overwritten and no longer exists in branch

2018-11-07 14:25 UTC, CampbellJGilpin commented on v2/AdminCore.Common/Interfaces/IEventService.cs
> +    EventDto FindById(int ID);
This file has been overwritten and no longer exists in branch

2018-11-07 15:12 UTC, CampbellJGilpin commented
Addressed most recent reviews - and resolved conflicts

2018-11-07 17:46 UTC, BrownMark requested changes

2018-11-07 17:46 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/TeamController.cs
> +        private List<TeamViewModel> mapTeamsToDtos(List<TeamDto> teams)
You don't need this method

2018-11-07 17:46 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/TeamController.cs
> +            return mapTeamsToDtos(_teamService.FindByClient(clientId));
this should be _mapper.Map<IList<TeamDto>, List<TeamViewModel>>(teams)

2018-11-09 09:25 UTC, eoinmcafee commented
Hey @CampbellJGilpin -  What's happening with this PR? Looks like there's conflicts and needs develop merged.

2018-11-09 10:00 UTC, CampbellJGilpin commented
@eoinmcafee @BrownMark 

Sorry, hadn't realized. Thanks for merging develop.

The two outstanding requests are addressed for TeamController

2018-11-09 10:30 UTC, eoinmcafee approved these changes

2018-11-09 10:31 UTC, BrownMark approved these changes

2018-11-09 10:31 UTC, merged