Feature/clients
UnosquareBelfast/AdminCore pull request #277
Opened 2018-11-06 14:08 UTC by mccleaveryan

- Stubbed methods for clients
- Repo calls and service methods to reflect Swagger and those within Java back end of adminCore

2018-11-06 16:25 UTC, BrownMark requested changes
Good work, just minor changes.

2018-11-06 16:25 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/ClientController.cs
> +    [HttpGet]
We'll need a specific route here.

2018-11-06 16:25 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/ClientController.cs
> +    [HttpGet]
We'll need a specific route here.

2018-11-07 10:36 UTC, eoinmcafee commented on v2/AdminCore.Common/Interfaces/IClientService.cs
> +    ClientDto GetClientByClientNameContaining(string clientName);
Not sure about the naming here, "containing". Should be fine just to say GetClientByClientName

2018-11-07 12:11 UTC, BrownMark approved these changes
Good work

2018-11-08 10:25 UTC, eoinmcafee commented
Nice and tidy code @mccleaveryan. Good job! happy to merge

2018-11-08 10:25 UTC, merged