Feature/stub out working from home
UnosquareBelfast/AdminCore pull request #279
Opened 2018-11-06 15:45 UTC by Jamie-Higgins

2018-11-06 16:25 UTC, BrownMark requested changes
Close :)

2018-11-06 16:25 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/WorkingFromHomeController.cs
> +    [HttpGet("/")]
Don't need the route here.

2018-11-07 09:25 UTC, eoinmcafee commented on v2/AdminCore.WebApp/Controllers/WorkingFromHomeController.cs
> +    [AllowAnonymous]
Can you remove all the allowed Anonymous please? If we want to test without auth we can just comment out the Authorize header at the top of the controller.

2018-11-07 10:48 UTC, BrownMark approved these changes

2018-11-07 10:48 UTC, merged