Task/wfh functionality and updating event service for future event types
UnosquareBelfast/AdminCore pull request #318
Opened 2018-12-10 11:00 UTC by Jamie-Higgins

Added Functionality and tests for working from home 
Added web mappings and removed duplicated web mapping
Made changes in the EventService and Interface to accept EventTypes to query for different types of event - also updated existing holiday code to reflect this change

2018-12-11 10:59 UTC, nmcmahon-unosquare requested changes

2018-12-11 10:59 UTC, nmcmahon-unosquare commented on v2/AdminCore.WebApp/Controllers/WorkingFromHomeController.cs
> +        return Ok(e.Message);
Return status code 500, log exception and return generic error message

2018-12-11 16:09 UTC, BrownMark commented on v2/AdminCore.WebApp/Controllers/WorkingFromHomeController.cs
> +      return Ok($"No Work From Home found for employee ID: { employeeId.ToString() }");
204 not found here please.

2018-12-11 16:12 UTC, nmcmahon-unosquare commented
Squash commits

2018-12-12 10:22 UTC, eoinmcafee approved these changes

2018-12-12 10:24 UTC, eoinmcafee commented on v2/AdminCore.WebApp/Controllers/WorkingFromHomeController.cs
> +      return Ok($"No Work From Home found for employee ID: { employeeId.ToString() }");
Can you address this one Jamie?

2018-12-12 10:42 UTC, nmcmahon-unosquare approved these changes

2018-12-12 10:42 UTC, merged