Logic for Half Days Implemented
UnosquareBelfast/AdminCore pull request #325
Opened 2018-12-12 15:01 UTC by Jamie-Higgins

Updated ints to doubles
Checks for single days that are also half days
Added check for if there are enough holidays before creating or updating event
Updated Tests
Updated Schema

*EventServiceTests > Splitting logic tests will fail as there is now a dependency on database mocking

2018-12-14 10:55 UTC, nmcmahon-unosquare requested changes

2018-12-14 10:55 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +        if (DoesEmployeeHaveEnoughHolidays(employeeId, eventToUpdate))
Personal preference - but If(EmployeeHasEnoughHolidays) reads better than if(DoesEmployeeHaveEnoughHolidays).
```suggestion
        if (EmployeeHasEnoughHolidays(employeeId, eventToUpdate))
```

2018-12-14 10:55 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +      double countHolidays = 0;
Method looks a bit bulky. Extract 229 - 234 into own method (maybe called GetNumberOfDaysFromEvents)

2018-12-14 10:55 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +        if (IsSameDay(eventDate) && eventDate.IsHalfDay)
Extract 347 - 354 into own method. Something like this
```suggestion
        totalDays += GetDaysFromEventDate(eventDate)
```

2018-12-14 10:55 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +    public void UpdateEvent(int employeeId, EventDateDto eventDateDto)
Method is 22 lines long with some nesting and if ladders. Consider breaking it down into smaller chunks

2018-12-14 10:55 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +      if (IsHalfDay(dates))
Same with this method, make these if-else blocks their own methods

2018-12-14 15:29 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/EventService.cs
> +        totalDays = GetDaysFromEventDate(eventDate, totalDays);
```suggestion
        totalDays += GetDaysFromEventDate(eventDate, totalDays);
```

2018-12-14 15:34 UTC, Jamie-Higgins commented on v2/AdminCore.Services/EventService.cs
> +        totalDays = GetDaysFromEventDate(eventDate, totalDays);
It passes in the variable in the method so += would be wrong. It would incriment the final result by the number of days

2018-12-17 11:39 UTC, nmcmahon-unosquare submitted a review, later dismissed

2018-12-21 11:00 UTC, unosquare-terrykernan approved these changes

2018-12-21 11:00 UTC, unosquare-terrykernan commented on v2/AdminCore.Common/Interfaces/IEventService.cs
> +    void UpdateEvent(int employeeId, EventDateDto eventDateDto);
do we need the employeeId here? doesn't eventDateDto have an EventDTO with an employeeId?

2018-12-21 11:00 UTC, unosquare-terrykernan commented on v2/AdminCore.Services/EventService.cs
>                    (startDate > x.StartDate && endDate > x.EndDate);
this seems a bit odd, it looks like it's checking for any start date (past or future) with an end date in the future?

2018-12-21 11:02 UTC, merged