Task/restore authenticated user
UnosquareBelfast/AdminCore pull request #349
Opened 2019-01-16 15:21 UTC by nmcmahon-unosquare

2019-01-16 15:24 UTC, BrownMark requested changes
Looks good, just minor suggestion

2019-01-16 15:24 UTC, BrownMark commented on v2/AdminCore.Services/AuthenticatedUser.cs
> +      var userDetails = GetLoggedInUserDetails();
Might be worth doing 2 things here:
1. Checking does that key exist in the dictionary.
2. store the key itself in a constants file (along with any other details we may query from the dictionary).

2019-01-17 11:26 UTC, nmcmahon-unosquare commented on v2/AdminCore.Services/AuthenticatedUser.cs
> +      var userDetails = GetLoggedInUserDetails();
Done

2019-01-21 13:29 UTC, nmcmahon-unosquare commented
Closing as new azure approach being used.

2019-01-21 13:29 UTC, closed without merging