File tree restructure
UnosquareBelfast/AdminCore pull request #4
Opened 2018-05-18 14:51 UTC by bgribz

The result of our Friday afternoon Mario Kart session.

- Massively cleans up the file tree
- Demonstrates how to use the container pattern
- Demonstrates cleaner imports/exports of components

There are still some improvements to be made, but I think this a good starting point for everyone to work off and move forward with.

Thoughts?

2018-05-18 15:24 UTC, William-Unosquare requested changes
Some bug fixes that stop it from running. Would fix this myself but indentation and stuff are different right now.

2018-05-18 15:24 UTC, William-Unosquare commented on web-app/src/components/RequestHoliday/container.js
> +import Swal from 'sweetalert2';
This needs removed and put at the top of the file

2018-05-18 15:24 UTC, William-Unosquare commented on web-app/src/components/TakenLeave/container.js
> +        <Wrapped takenHolidays={this.state.takenHolidays} {...props} />
Change `{...props}` to `{...this.props}`

2018-05-18 15:24 UTC, William-Unosquare commented on web-app/src/components/BookedLeave/container.js
> +        <Wrapped bookedHolidays={this.state.bookedHolidays} {...props} />
Change `{...props}` to `{...this.props}`

2018-05-18 15:33 UTC, William-Unosquare approved these changes

2018-05-21 10:34 UTC, BrownMark approved these changes

2018-05-21 10:34 UTC, merged